# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 01:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APNService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('certificate', models.TextField()),
                ('private_key', models.TextField()),
                ('passphrase', django_fields.fields.EncryptedCharField(blank=True, block_type=b'MODE_CBC', help_text=b'Passphrase for the private key', max_length=110, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=30, null=True)),
                ('display', models.CharField(blank=True, max_length=30, null=True)),
                ('os_version', models.CharField(blank=True, max_length=20, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ios_notifications.APNService')),
                ('users', models.ManyToManyField(blank=True, related_name='ios_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('apn_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ios_notifications.APNService')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, help_text=b'Alert message to display to the user. Leave empty if no alert should be displayed to the user.', max_length=200)),
                ('badge', models.PositiveIntegerField(blank=True, help_text=b'New application icon badge number. Set to None if the badge number must not be changed.', null=True)),
                ('silent', models.NullBooleanField(help_text=b'set True to send a silent notification')),
                ('sound', models.CharField(blank=True, help_text=b'Name of the sound to play. Leave empty if no sound should be played.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('custom_payload', models.CharField(blank=True, help_text=b'JSON representation of an object containing custom payload.', max_length=240)),
                ('loc_payload', models.CharField(blank=True, help_text=b'JSON representation of an object containing the localization payload.', max_length=240)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ios_notifications.APNService')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='apnservice',
            unique_together=set([('name', 'hostname')]),
        ),
        migrations.AlterUniqueTogether(
            name='feedbackservice',
            unique_together=set([('name', 'hostname')]),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('token', 'service')]),
        ),
    ]
